### ISSUE TITLE
Brainstorming calibration pipelines

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/CalibrateEDMF.jl#189]
I was talking with @haakon-e about some ideas I've had about calibrating.

Based on our existing TC compilation time, it'd be really useful to preserve a julia session across calibration updates. Let's look at the data. Here are the results of TC.jl's `measure precompilation speedup (all)` buildkite job, which runs `main` twice in the same session, given a namelist (code snippet [here](https://github.com/CliMA/TurbulenceConvection.jl/blob/0624546606ce8379f23fb1190e6cefb68b0ff17d/perf/precompilable.jl#L6-L14)):

```
# First @time of `main` in a fresh session
175.137718 seconds (317.25 M allocations: 15.550 GiB, 5.15% gc time, 92.09% compilation time)

# Second @time of `main` in the same session
14.070870 seconds (1.02 M allocations: 93.997 MiB)
```

The second run is ~12.44x faster.

We can further speed things up by reducing the number of fields that we export, and only allocating once, but maintaining a fresh session will collapse ~90% of our TC runtime, which is presumably the expensive part. I think that's the first thing to aim at.

The way I figure we could do this (we may need to iron out some details), would be with a runner script that looks something like this:

```julia
# TCRunner.jl
while true
    params_updated, terminate = read(watch_file) # continuously watch a file
    if terminate
        cleanup() # deallocate, close up shop
        exit()
    end
    if params_updated
        # namelist has been updated by main processor
        namelist = read(namelist_file)
        main(namelist) # run TC.jl, maybe need try-catch?
        # NC file now available
        write(watch_file) # update `Bool`s: solve_finished = true, success = true / false
    end
    # Calibration update occurs in calibrator script on main processor
    sleep(.1 #=second=#) # don't waste clock cycles
end
```
and a "main" processing file that handles editing the file `watch_file`.

For calibration, we could have two modes of running

## Single top-level script

@haakon-e suggested would be good to be able to run from from a MWE-sort of script. For this script, I suppose it would be something similar to our existing `pmap` script-- I'm not yet familiar enough to know we'd need to communicate to each processor but, when we do, we can
 - Launch each processor to run `TCRunner.jl`
 - edit the file `watch_file` appropriately on each processor from `CalibrateScriptMWE.jl` (on the main processor)

## Fully automated pipeline

For the fully automated pipeline, we would have something similar to `CalibrateScriptMWE.jl` (say `CalibrateScript.jl`), except that we may need to manage where files are written to disk differently.

I imagine we could semi-manually (or programmatically) configure the buildkite pipeline. The simplest thing I can think of now would be to have something like this:

```yml
env:
  JULIA_VERSION: "1.7.0"
  ...

steps:
  - label: "init environment :computer:"
    command:
      - "julia --project=test -e 'using Pkg; Pkg.develop(path = \".\")'"
      - "julia --project=test -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=test -e 'using Pkg; Pkg.status()'"
      ...

  - wait

  - label: "Runner 1"
    command:
      - "julia --color=yes --project=test TCRunner.jl --runner=1"
    agents: ...

  - label: "Runner 2"
    command:
      - "julia --color=yes --project=test TCRunner.jl --runner=2"
    agents: ...

  - label: "Runner 3"
    command:
      - "julia --color=yes --project=test TCRunner.jl --runner=3"
    agents: ...

  - label: "main_process"
    command:
      - "julia --color=yes --project=test CalibrateScript.jl" # monitor, then manage runner 1, 2, 3,...
    agents: ...

  - wait

  - label: "post_process"
    command:
      - "julia --color=yes --project=test post_process.jl"
    artifact_paths:
      - "output/*"
    agents: ...
```
This would mean that the calibration results could automatically appear in buildkite, like what we have in TC.jl. 

The coolest part of having this configured is that we could trivially calibrate experimental TC branches by replacing
```yml
      - "julia --project=test -e 'using Pkg; Pkg.develop(path = \".\")'"
```
with
```yml
      - "julia --project=test -e 'using Pkg; Pkg.add(PackageSpec(name="TurbulenceConvection", rev="my_test_branch"))'"
      - "julia --project=test -e 'using Pkg; Pkg.develop(path = \".\")'"
```

What do people think? cc @haakon-e, @ilopezgp, @yairchn, @costachris
